
# site settings
title: Yuto Noji Portfolio
subtitle: by FORTY
email: yuuto1228u@gmail.com
description: このサイトはYuto Nojiのポートフォリオサイトです。<br>経歴やスキル、開発物などの情報を掲載しています。お気軽にご連絡ください！<br>製作途中につき、挙動がおかしい点や情報不足は見逃して！
baseurl: "" 
url: "https://yunyun.jp"
google_analytics: UA-168643865-1

qiita: https://qiita.com/H_Ny
street_address: private
phone: Private

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:

##googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://www.instagram.com/yuuto_x9/
twitter_url: https://twitter.com/yuto_noji
github: https://github.com/yuuto1228
# build settings
markdown: kramdown

sass:
  style: compressed
